### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by juhaelee** [niklasvh/html2canvas-proxy#1]
I created a google app using the open source code and deployed it. I changed the proxy addresses in the jquery.plugin.html2canvas.js and screenshots.html. Then I tried to run screenshots.html, but it didn't work. Is there something else I should be doing?

**Comment by niklasvh** [comment]
Is the proxy returning any error? Could you post the link here or send me in private and I'll have a look.

**Comment by juhaelee** [comment]
I don't believe the proxy is returning an error, I just messaged you the link
